hackclub/OnBoard

docs/faq.md
*ps: love the PR template*
Yeah some needed updates because people **will** ask for 250$ if you forget about it in the FAQ
=> faq: Onboardify the faq

docs/faq.md
I think this was a typo– we talk about $100 in other areas
=> Update grant size 1k -> $100

TIPS.md
Added `TIPS.md` for free advice! No need to learn the hard way!
=> Add TIPS.md

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a link to the verification form so we don't have to wait on the greeter bot to link it.
=> Add verification form to PR template

TIPS.md
Created a new tip to help our fellow onboard participants save more on PCB orders !
=> Added a tip to tips.md

.github/workflows/pr-greeter.yml, .github/workflows/requisite_check.yml
See convo on Slack https://hackclub.slack.com/archives/C056AMWSFKJ/p1685556916382919
cc @maxwofford
=> Only run pr-greeter workflow when the projects directory is touched

projects/Soumay's card/README.md
[gerber.zip](https://github.com/hackclub/OnBoard/files/11726129/gerber.zip)
[bom.csv](https://github.com/hackclub/OnBoard/files/11726132/bom.csv)
[picknplace.csv](https://github.com/hackclub/OnBoard/files/11726133/picknplace.csv)
=> Soumay's Card

docs/faq.md
adding no customs reimbursement policy into FAQs suggested by Alex
=> Update faq.md w/ customs, fix grammar prob

meta/QUOTES.md
We reached out to both of them about OnBoard. Sounds like they like it!
=> Add quotes from Steve Woz & Dean Kamen about OnBoard

meta/2023-11-21_RFC_GRANT_RESTRUCTURE.md
Zach had a good one-liner for this change: "$100 grant to make your own board, or $40 to make one of ours"
=> RFC grant restructuring

projects/Alex P's NFC Card/README.md
FYI: I used the HTML <img> tag because markdown does not allow you to control how big the image is displayed, and it was way too big.
=> Add image to my submission (Alex P's NFC Card)

.github/workflows/pull_request_gerbview.yml
=> Silly mistake in bot

.github/workflows/requisite_check.yml
=> Update requisite_check GH action to more recent node version

.github/PULL_REQUEST_TEMPLATE.md
Updated template to be more clear about what files are needed, as asked by Karmanyaah. Will also be making a pr to the onboard jam.
=> Update pull request template 

examples/site/index.html
=> adding ingredients to recipe page

docs/VENDORS.md
Hi there!
In VENDORS.md, it says
> grant can't cover additional merchants like customs
I fixed it to be:
> grant can't cover additional charges like customs
=> Fix typo in VENDORS.md

.github/workflows/gerbview.js
Small QoL improvements. Best viewed by commit
=> Make schematic.pdf checking clearer

README.md
small wording change. plz merge.
=> Make it clear Woz gave this quote for OnBoard

README.md
=> change slack channel from #onboard to #electronics

docs/faq.md
=> AFAIK We are not doing team projects

README.md
=> Fix grammatical error!

.github/labeler.yml
=> Revert "Update labeler.yml"

showcase/package-lock.json, showcase/package.json, showcase/src/lib/components/App.svelte, showcase/src/lib/components/Scene.svelte, showcase/src/lib/components/models/pcb.svelte, showcase/src/routes/+page.svelte
=> Fixed Mobile Overflow Issue

showcase/src/routes/+page.svelte
=> small website formatting changes

showcase/src/routes/+page.svelte, showcase/vite.config.ts
=> maybe fix vite error?

showcase/src/app.html
=> opengraph and theme color

showcase/src/app.html, showcase/src/routes/+page.svelte
=> fix mobile 

showcase/src/app.html, showcase/src/routes/+page.svelte
@LimesKey Contributing to Showcase Website.
=> Showcase Website Update

.github/PULL_REQUEST_TEMPLATE.md, showcase/README.md, showcase/src/app.html, showcase/src/routes/+page.svelte, showcase/static/README.md
=> Launch of Trick or Trace

showcase/src/routes/+page.svelte
=> add faq thing

.github/PULL_REQUEST_TEMPLATE.md, meta/nginx.conf, showcase/src/app.html, showcase/src/routes/+page.svelte
This PR adds in a Slack Bridge to the Verification form for users to submit at the start of every OnBoard Pull Request. It has been a while in the making, but I recently had the time to finally deploy it at last. See the source code [here](https://github.com/LimesKey/hackclub-ysws-verifier). It's built on Cloudflare Wrangler and Slack OAuth V2. I am requesting the exact same Slack permissions as Low Skies and other YSWS projects use, nothing more.
Check it out here, https://verify.onboard.hackclub.com. I've made sure to also keep the old form as a "Legacy" form at https://legacy.verify.onboard.hackclub.com in case the new form catastrophically fails. Closes #1034.
=> Introduce revised Fillout Verification Form & Open Submissions for Trick or Trace

showcase/src/routes/+page.svelte
=> update date again

docs/faq.md
Removes all mentions to Hack Club Bank
=> FIX: Remove wording of Hack Club Bank and rewrite a bit to make it better

showcase/README.md, showcase/static/README.md
=> clarify submission date

showcase/package.json, showcase/pnpm-lock.yaml, showcase/src/lib/components/Slack.svelte, showcase/src/routes/+page.svelte, showcase/src/routes/api/submissions/+server.ts, showcase/src/routes/api/vote/+server.ts, showcase/src/routes/oauth/slack/+server.ts, showcase/src/routes/showcase/+page.svelte, showcase/vite.config.ts
Implement the voting page for Trick or Trace at https://trickortrace.hackclub.com/showcase
=> Trick or Trace Voting

showcase/src/routes/+page.svelte
=> voting clarification

showcase/src/routes/showcase/+page.svelte
=> look better for mobile

showcase/src/routes/showcase/+page.svelte
=> oops quick bug fix

showcase/src/routes/api/submissions/+server.ts, showcase/src/routes/showcase/+page.svelte
=> omit heaings

README.md
=> remove mention of trick or trace in readme

.github/PULL_REQUEST_TEMPLATE.md
=> remove trick or trace from pull request template

.github/labeler.yml, README.md
Adds in the announcement that Hacky Holidays is running and put it in the main README with some instructions for submitting a pull request.
=> Annoucement of Hacky Holidays into main README

projects/!Template/README.md
=> Update template README to use correct gerber filename

.github/PULL_REQUEST_TEMPLATE.md
=> Typo in pr template

README.md
* RGB_C
* Delete projects/rgb_strip_controller/src/fp-info-cache
* Add files via upload
* Update README.md
* Update README.md
* added end
* end
* Update README.md
* Update README.md
* heading h2
* Update README.md
___
=> fix (#1739)
